import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/stywes/globals.scss";
import { Navbar } from "@/componyents";
import NoSSRWrapper from '@/wibs/nossrwrapper';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NoSSRWrapper>
          <Navbar />
          {children}
        </NoSSRWrapper>
      </body>
    </html>
  );
}

export default RootLayout;